Repository frdedynamics/find_the_duck, pull requests merged in 2024-09, with the labels that each got.

#9 add newline at end
  _config_prod.yml
Labels: bug

#11 10 fix alert dom text reinterpreted as html
  _layouts/home.html
Labels: security :police_officer:

#13 Updata to v1.1.4
  CHANGELOG.md
  _sass/_base.scss
  _sass/_layout.scss
  bay_jekyll_theme.gemspec
Labels: dependencies

#17 Remove secrets from repo but still in plain sight in deployed static site, and replace deploy workflow with less third party
  .github/workflows/deploy.yml
  .github/workflows/jekyll-gh-pages.yml
  _config.yml
  _config_prod.yml
Labels: dependencies, github_actions, security :police_officer:
